#!/usr/bin/env python
"""HISTORICAL 19 — freeze the cross-validation fold assignment to a file.

WHY. hist14 and hist18 both draw their folds from `np.random.default_rng(42)`,
but they consume that generator in DIFFERENT ORDERS -- hist14 draws two block
scales, hist18 draws five -- so the same seed produced different partitions and
the 1 km blocked RMSE came out as 2.761 m in one and 2.784 m in the other. The
0.023 m gap is only fold-assignment noise, but a canonical number should not
depend on how many other draws a script happens to make first.

So the partition becomes DATA, not a side effect of call order.

REPRODUCING THE CANONICAL PARTITION. The three schemes hist14 already uses are
regenerated by replaying its exact RNG sequence:

    1. RNG.choice(n, 1500, replace=False)        the variogram subsample
    2. RNG.permutation(unique 1 km block ids)    blocked1km
    3. RNG.permutation(unique 5 km block ids)    blocked5km
    4. RNG.integers(0, 10, n)                    random

Step 1 draws nothing used here but MUST be replayed, because it advances the
generator. The two additional scales hist18 wanted (0.5 km, 2 km) are drawn
only AFTER all four steps, so they cannot perturb the canonical three.

The script then asserts that its blocked1km partition reproduces hist14's
published OK score of 2.7613 m, and refuses to write the file if it does not.

Outputs
-------
data/processed/bathymetry/hist14_cv_fold_assignments.parquet
"""
from __future__ import annotations

import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

import numpy as np
import pandas as pd

from swot_dnipro import config as CFG

import hist14_bed_surface as H14

DST = CFG.BULK_ROOT / "data_swot/processed/bathymetry/hist14_cv_fold_assignments.parquet"
CANONICAL_OK_RMSE = 2.7613048945293444   # hist14_interpolator_cv.csv, blocked1km
N_FOLDS = H14.N_FOLDS
SEED = CFG.SEED
# hist14's order first, then the extra scales. Order is the whole point.
CANONICAL_BLOCKS = [1.0, 5.0]
EXTRA_BLOCKS = [0.5, 2.0]


def load_soundings():
    """Exactly hist14's loader, including the duplicate averaging and its
    deterministic groupby ordering."""
    sd = pd.read_parquet(CFG.BULK_ROOT / "data_swot/processed/bathymetry/"
                                "kakhovka_soundings_evrf2019.parquet")
    n0 = len(sd)
    sd = sd.assign(_kx=sd.x.round(0), _ky=sd.y.round(0)).groupby(
        ["_kx", "_ky"], as_index=False).agg(
        x=("x", "mean"), y=("y", "mean"), lon=("lon", "mean"),
        lat=("lat", "mean"), H_bed_evrf2019_m=("H_bed_evrf2019_m", "mean"))
    return sd, n0


def block_folds(xy, km, rng):
    bid = pd.factorize([tuple(b) for b in
                        np.floor(xy / (km * 1000)).astype(int)])[0]
    ub = np.unique(bid)
    bf = dict(zip(rng.permutation(ub), np.arange(len(ub)) % N_FOLDS))
    return np.array([bf[b] for b in bid]), len(ub)


def main() -> None:
    sd, n0 = load_soundings()
    xy = np.c_[sd.x.values, sd.y.values]
    z = sd.H_bed_evrf2019_m.values
    n = len(sd)
    print(f"{n:,} soundings ({n0:,} raw, {n0-n} duplicate coordinates averaged)")

    rng = np.random.default_rng(SEED)

    # ---- step 1: replay the variogram subsample. Consumed, not stored. -----
    sub = rng.choice(n, min(1500, n), replace=False)
    print(f"replayed the variogram subsample ({len(sub)} points) to advance "
          f"the generator")

    out = {"point_id": np.arange(n, dtype=np.int32),
           "x": sd.x.values, "y": sd.y.values,
           "lon": sd.lon.values, "lat": sd.lat.values,
           "H_bed_evrf2019_m": z}

    # ---- steps 2-3: the canonical block scales, in hist14's order ----------
    nblocks = {}
    for km in CANONICAL_BLOCKS:
        f, nb = block_folds(xy, km, rng)
        out[f"block_{km:g}km_fold".replace(".", "p")] = f.astype(np.int8)
        nblocks[km] = nb
        print(f"  blocked{km:g}km : {nb:,} blocks -> {N_FOLDS} folds  "
              f"[CANONICAL]")

    # ---- step 4: random ----------------------------------------------------
    out["random_fold"] = rng.integers(0, N_FOLDS, n).astype(np.int8)
    print(f"  random      : {N_FOLDS} folds  [CANONICAL]")

    # ---- extra scales, drawn only after everything canonical ---------------
    for km in EXTRA_BLOCKS:
        f, nb = block_folds(xy, km, rng)
        out[f"block_{km:g}km_fold".replace(".", "p")] = f.astype(np.int8)
        nblocks[km] = nb
        print(f"  blocked{km:g}km : {nb:,} blocks -> {N_FOLDS} folds  "
              f"[added after the canonical draws]")

    df = pd.DataFrame(out)
    df["seed"] = SEED
    df["n_folds"] = N_FOLDS

    # ================================================== verify against hist14
    # Run ordinary kriging on the reproduced 1 km partition and require the
    # published score. If this fails the partition is NOT hist14's and writing
    # the file would silently redefine the canonical number.
    print("\nverifying the reproduced blocked1km partition against "
          f"hist14's published score {CANONICAL_OK_RMSE:.4f} m")
    import skgstat as skg
    V = skg.Variogram(xy[sub], z[sub], model="spherical", n_lags=20,
                      maxlag=0.35, normalize=False)
    vg = (float(V.parameters[0]), float(V.parameters[1]),
          float(V.parameters[2]) if len(V.parameters) > 2 else 0.0)
    print(f"  variogram: range {vg[0]/1000:.2f} km, sill {vg[1]:.2f}, "
          f"nugget {vg[2]:.2f} m2")

    folds1 = df["block_1km_fold"].values
    resid = np.full(n, np.nan)
    for f in range(N_FOLDS):
        te = folds1 == f
        if te.sum() == 0 or (~te).sum() < 50:
            continue
        pred = H14.METHODS["OK"](xy[~te], z[~te], xy[te], vg)
        resid[te] = pred - z[te]
    r = resid[np.isfinite(resid)]
    rmse = float(np.sqrt((r ** 2).mean()))
    print(f"  reproduced RMSE {rmse:.7f} m   published "
          f"{CANONICAL_OK_RMSE:.7f} m   diff {1e3*(rmse-CANONICAL_OK_RMSE):+.4f} mm")
    if abs(rmse - CANONICAL_OK_RMSE) > 1e-6:
        raise SystemExit(
            "REFUSING TO WRITE: the reproduced blocked1km partition does not "
            "match hist14's published score. The RNG replay order is wrong, or "
            "the soundings file has changed. Fix that before freezing folds -- "
            "writing this file would silently redefine the canonical RMSE.")
    print("  MATCH -- this is hist14's partition, bit for bit")

    df.to_parquet(DST, index=False)
    print(f"\nfold sizes (should be ~{n//N_FOLDS} each):")
    for c in [c for c in df.columns if c.endswith("_fold")]:
        vc = df[c].value_counts().sort_index()
        print(f"  {c:<20}min {vc.min():>5}  max {vc.max():>5}  "
              f"spread {vc.max()-vc.min():>5}")
    print(f"\n-> {DST}  ({DST.stat().st_size/1024:.0f} kB)")
    print("\n  hist14 and hist18 should now READ this file instead of drawing "
          "folds,\n  so the canonical 2.761 m no longer depends on RNG call "
          "order.")


if __name__ == "__main__":
    main()
